CREATE TABLE Child(ChildID INTEGER PRIMARY KEY NOT NULL, CFirstName VARCHAR2(20), CLastName VARCHAR2(20), CAddress VARCHAR2(200), CEmail VARCHAR2(20), CMobile NUMBER(11));

CREATE TABLE Staff(StaffID INTEGER PRIMARY KEY NOT NULL, SFirstname VARCHAR2(20), SFirstname VARCHAR2(20), SMobile NUMBER(11),SHomePhone NUMBER(11), SEmail VARCHAR2(20), SAddress VARCHAR2(200), isNurse NUMBER(1));

CREATE TABLE Sit(SitID INTEGER PRIMARY KEY NOT NULL, StartTime VARCHAR2(5), EndTime VARCHAR2(5),StartDate VARCHAR2(10), EndDate VARCHAR2(10),ChildID foreign KEY REFERENCES Child(ChildID));

CREATE TABLE Staff_Child_Link(StaffID INTEGER FOREIGN KEY REFERENCES Staff(StaffID), ChildID INTEGER FOREIGN KEY REFERENCES Child(ChildID));

CREATE TABLE Staff_Sit_Link(StaffID INTEGER FOREIGN KEY REFERENCES Staff(StaffID), SitID INTEGER FOREIGN KEY REFERENCES Sit(SitID));